service: pdf-generate-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, "dev"}
  region: ap-south-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
    stages:
      - dev
      - prod
    mongouri:
      dev: ${env:DEV_MONGO_URI}
      prod: ${env:PROD_MONGO_URI}
    mongouser:
      dev: ${env:DEV_MONGO_USER}
      prod: ${env:PROD_MONGO_USER}
    mongopassword:
      dev: ${env:DEV_MONGO_PASSWORD}
      prod: ${env:PROD_MONGO_PASSWORD}

functions:
  app:
    timeout: 900
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true

    environment:
      mongoUri: ${self:custom.mongouri.${self:provider.stage}}
      mongoUser: ${self:custom.mongouser.${self:provider.stage}}
      mongoPassword: ${self:custom.mongopassword.${self:provider.stage}}
      # mongoUri: ${env:MONGO_URI}
      # mongoUser: ${env:MONGO_USER}
      # mongoPassword: ${env:MONGO_PASSWORD}
