service: pdf-generate-app

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-south-1

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
functions:
  app:
    timeout: 2000
    handler: app.server # reference the file and exported method
    events: # events trigger lambda functions
      - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
      - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true
    
    environment:
      mongoUri: ${env:MONGO_URI}
      mongoUser: ${env:MONGO_USER}
      mongoPassword: ${env:MONGO_PASSWORD}